// Generated by ReScript, PLEASE EDIT WITH CARE


function to_eqx(x) {
  if (typeof x === "object") {
    return {
            maxStaleMs: x._0
          };
  }
  switch (x) {
    case "RequireLoad" :
        return {
                requireLoad: true
              };
    case "RequireLeader" :
        return {
                requireLeader: true
              };
    case "AnyCachedValue" :
        return {
                maxStaleMs: 9007199254740991
              };
    case "AssumeEmpty" :
        return {
                assumeEmpty: true
              };
    
  }
}

export {
  to_eqx ,
}
/* No side effect */
