// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "crypto";

var $$Crypto$1 = {};

var TimelineEvent = {};

function toTimelineEvent(index, ev) {
  var x = ev.id;
  var id = x !== undefined ? x : $$Crypto.randomUUID();
  var time = new Date();
  return {
          id: id,
          time: time,
          type: ev.type,
          data: ev.data,
          meta: ev.meta,
          index: index,
          isUnfold: false,
          size: 0
        };
}

var EventData = {
  toTimelineEvent: toTimelineEvent
};

export {
  $$Crypto$1 as $$Crypto,
  TimelineEvent ,
  EventData ,
}
/* crypto Not a pure module */
