// Generated by ReScript, PLEASE EDIT WITH CARE


function json(encode, tryDecode) {
  var tryDecode$1 = function (ev) {
    return tryDecode([
                ev.type,
                ev.data
              ]);
  };
  var encode$1 = function (ev, ctx) {
    var match = encode(ev, ctx);
    return {
            type: match[0],
            data: match[1]
          };
  };
  return {
          tryDecode: tryDecode$1,
          encode: encode$1
        };
}

export {
  json ,
}
/* No side effect */
