// Generated by ReScript, PLEASE EDIT WITH CARE


async function sendEmail(to, title, body) {
  console.log("To: ", to, "Title: ", title, "Body: ", body);
}

var Memory = {
  sendEmail: sendEmail
};

export {
  Memory ,
}
/* No side effect */
