name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

env:
  # AWS Credentials
  AWS_ACCESS_KEY_ID: local
  AWS_SECRET_ACCESS_KEY: local
  AWS_DEFAULT_REGION: local
  AWS_REGION: local

jobs:
  build-test-lint:
    name: Build, test, lint
    runs-on: ubuntu-latest
    services:
      dynamo:
        image: "amazon/dynamodb-local:latest"
        ports:
          - "8000:8000"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm dlx turbo build

      - name: Test
        run: pnpm dlx turbo test

      - name: Lint
        run: pnpm dlx turbo lint
